Repository arqma/arqma, pull requests merged in 2019-04, with the labels that each got.

#99 rpc.getblocktemplate: set reserved_offset to zero when reserve_size==0 #5428
  src/rpc/core_rpc_server.cpp
  tests/performance_tests/performance_utils.h
Labels: correct

#92 more clear help text
  contrib/epee/include/string_tools.h
  src/simplewallet/simplewallet.cpp
Labels: Work In Progress

#106 blockchain poisson + various fixes
  .travis.yml
  Dockerfile
  Makefile
  README.md
  src/common/int-util.h
  src/cryptonote_config.h
  src/cryptonote_core/blockchain.cpp
  src/cryptonote_core/cryptonote_core.cpp
  src/cryptonote_core/cryptonote_tx_utils.cpp
  src/cryptonote_protocol/cryptonote_protocol_handler.inl
Labels: correct, enhancement
