Repository arqma/arqma, pull requests merged in 2019-05, with the labels that each got.

#118 Update socks.cpp
  src/net/socks.cpp
Labels: testing

#109 new algo for tests
  Doxyfile
  README.md
  contrib/depends/builders/darwin.mk
  contrib/depends/packages/cmake/conf/mxe-conf.cmake.in
  contrib/depends/packages/cmake/conf/target-cmake.in
  contrib/depends/packages/cmake/test/CMakeLists.txt
  contrib/epee/include/misc_language.h
  contrib/epee/include/net/abstract_tcp_server2.h
  contrib/epee/include/net/abstract_tcp_server2.inl
  contrib/epee/include/net/levin_protocol_handler_async.h
  contrib/epee/include/net/levin_server_cp2.h
  contrib/epee/include/net/net_utils_base.h
  contrib/epee/include/net/network_throttle-detail.hpp
  contrib/epee/include/net/network_throttle.hpp
  contrib/epee/include/net/protocol_switcher.h
  contrib/epee/include/span.h
  contrib/epee/src/connection_basic.cpp
  src/common/threadpool.cpp
  src/common/threadpool.h
  src/crypto/CMakeLists.txt
  src/crypto/chacha.h
  src/crypto/hash-ops.h
  src/crypto/hash.h
  src/crypto/slow-hash.c
  src/crypto/variant2_int_sqrt.h
  src/cryptonote_basic/cryptonote_format_utils.cpp
  src/cryptonote_core/blockchain.cpp
  src/simplewallet/simplewallet.cpp
  src/version.cpp.in
  src/wallet/wallet2.cpp
Labels: Work In Progress

#121 few minor performance tweaks
  src/common/base58.cpp
  src/common/base58.h
  src/cryptonote_basic/cryptonote_basic_impl.cpp
  src/cryptonote_basic/cryptonote_basic_impl.h
  src/cryptonote_core/blockchain.cpp
  src/cryptonote_core/cryptonote_tx_utils.cpp
  src/cryptonote_core/cryptonote_tx_utils.h
  src/ringct/rctSigs.cpp
  src/ringct/rctSigs.h
  src/rpc/daemon_messages.cpp
  src/simplewallet/simplewallet.cpp
  src/wallet/wallet2.cpp
  src/wallet/wallet2.h
Labels: Need to be Tested

#124 Rpc
  src/rpc/core_rpc_server.cpp
  src/rpc/core_rpc_server_commands_defs.h
Labels: testing
